meals = [
    'Pizza',
    'Burgers',
    'BLTs',
    'Dinner Salads',
    'Falafel',
    'Scrambled Eggs, Bacon, Bagels, and Avocado',
    'Sushi',
    'Taco Bowls',
    'Fajitas',
    'Pork Tenderloin and Cheesy Polenta',
    'Salmon and Rice',
    'Schnitzel and Brussels Sprouts',
    'Roast Chicken and Potatoes',
    'Korean Pork Bowls',
    'Fried Tofu and Eggplant',
    'Sauteed Chicken with Duxelles and Thyme Cream Sauce',
    'Pasta Salad',
    'Souvlaki and Greek Salad',
    'Penne Puttanesca and Meatballs',
    'Braised Beef',
    'Vegetable Lasagna',
    'Angel Hair Pasta with Zucchini',
    'Kebabs',
    'Paninis',
    'Chili',
    'Chicken Noodle Soup',
    'Potato Leek Soup',
    'Parsi Chicken',
    'Fried Chicken and Mashed Potatoes',
    'Korean Fried Chicken'
]
